# Generated by Django 2.2.7 on 2020-03-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QaList',
            fields=[
                ('QAINDEX', models.IntegerField(primary_key=True, serialize=False)),
                ('CLINIX', models.TextField()),
                ('QUESTION', models.TextField()),
                ('ANSWER', models.TextField()),
                ('SNAPSHOT', models.DateField()),
            ],
        ),
    ]
