# Generated by Django 2.2.7 on 2020-03-21 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qalist',
            old_name='CLINIX',
            new_name='CLINIC',
        ),
    ]
