# Generated by Django 2.2.7 on 2020-05-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0002_auto_20200321_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDemo',
            fields=[
                ('q_index', models.IntegerField(primary_key=True, serialize=False)),
                ('question_user', models.TextField()),
                ('answer_user', models.TextField()),
                ('quest_date', models.DateTimeField(verbose_name='date published')),
                ('pre_method', models.IntegerField()),
            ],
        ),
    ]
