# Generated by Django 2.2.7 on 2020-05-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0003_questiondemo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiondemo',
            old_name='answer_user',
            new_name='ANSWER_USER',
        ),
        migrations.RenameField(
            model_name='questiondemo',
            old_name='pre_method',
            new_name='PRE_METHOD',
        ),
        migrations.RenameField(
            model_name='questiondemo',
            old_name='question_user',
            new_name='QUESTION_USER',
        ),
        migrations.RenameField(
            model_name='questiondemo',
            old_name='quest_date',
            new_name='QUEST_DATETIME',
        ),
        migrations.RenameField(
            model_name='questiondemo',
            old_name='q_index',
            new_name='Q_INDEX',
        ),
    ]
