# Generated by Django 2.2.7 on 2020-05-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0004_auto_20200503_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondemo',
            name='Q_INDEX',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
