# Generated by Django 2.2.7 on 2020-05-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0005_auto_20200503_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='QaAdmin',
            fields=[
                ('Qa_INDEX', models.AutoField(primary_key=True, serialize=False)),
                ('QUESTION_ADMIN', models.TextField()),
                ('ANSWER_ADMIN', models.TextField()),
                ('QA_DATETIME', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
